### PR TITLE
Fix make test-lint

### LINKED ISSUE #506: `make test` fails on linter
`make test` doesn't run unit tests due to a number of linter failures:

```
$ make test
scripts/lint.sh
Manadatory Linters: These must pass
pkg/draftd/portforwarder/portforwarder.go:1::warning: file is not gofmted with -s (gofmt)
pkg/linguist/static.go:1::warning: file is not gofmted with -s (gofmt)
pkg/linguist/data/data.go:1::warning: file is not gofmted with -s (gofmt)
pkg/linguist/tokenizer/tokenizer.go:1::warning: file is not gofmted with -s (gofmt)
cmd/draft/init_test.go:63:21:warning: "registy" is a misspelling of "registry" (misspell)
...
```

Most of these are quick fixes, so I'll knock them out and try to clean up the other optional linter errors, too.

### PR DESCRIPTION
**Pull request by seanknox**
This fixes a number of minor linting errors, with the goal to be able to run `make test-lint` (and thus `make test`) successfully and use it a source of truth. ☮️ 

Following are still TBD...would appreciate help with comments. Feel free to shoot them to me or commit to this branch directly.
```
cmd/draft/installer/installer.go:16:6:warning: exported type Installer should have comment or be unexported (golint)
cmd/draft/installer/installer.go:22:6:warning: exported type Interface should have comment or be unexported (golint)
cmd/draft/installer/installer.go:27:1:warning: exported function New should have comment or be unexported (golint)
pkg/build/watch.go:16:1:warning: exported method Context.Watch should have comment or be unexported (golint)
pkg/draft/client.go:29:6:warning: exported type Client should have comment or be unexported (golint)
pkg/draft/client.go:52:1:warning: exported method Client.Results should have comment or be unexported (golint)
pkg/draft/client.go:54:1:warning: exported method Client.Version should have comment or be unexported (golint)
pkg/draft/client.go:58:1:warning: exported method Client.Up should have comment or be unexported (golint)
pkg/draft/context.go:21:6:warning: exported type AppContext should have comment or be unexported (golint)
pkg/linguist/tokenizer/tokenizer.go:47:2:warning: exported var StartLineComment should have comment or be unexported (golint)
```

Fixes #506.

### CODE REVIEW

File: pkg/kube/podutil/podutil.go [hunk 1]
```diff
@@ -9,7 +9,7 @@ func IsPodReady(pod *v1.Pod) bool {
 	return IsPodReadyConditionTrue(pod.Status)
 }
 
-// IsPodReady retruns true if a pod is ready; false otherwise.
+// IsPodReadyConditionTrue retruns true if a pod is ready; false otherwise.
```
Comment (bacongobbler) [inline pkg/kube/podutil/podutil.go]: returns*

nice catch!

**Comment by bacongobbler** [comment]
I'll see if I can come up with a few docstrings for those packages. :)
